#travis will need sudo access
sudo: required

#travis install copy of docker
services:
  - docker

before_install:
  - docker build -t konstantinos-chronis/docker-react -f Dockerfile.dev .

#commands that needed to run the test suite
script:
  - docker run -e CI=true konstantinos-chronis/docker-react npm run test